# name=input('请输入')
# print("输入为:",name)
# number=input('输入数字')
# number=int(number)
# print('数字类型是：',type(number))
username=input('请输入用户名')
usertype=input('请输入用户类型')
print(f"{username}您好，您是{usertype}用户")